### PR TITLE
full feature of mint signup clone

### PR DESCRIPTION
**Pull request by ricardo123321**
we created a form copy page of mint sign up page

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @ricardo123321, @tacodtripe. Impressive effort on this project:+1:. Let's take care of the following:**
1. You have the wrong linter files in your project folder. Please check it.

2. You haven't enabled stickler for this repo yet. Please do so and fix all errors that might arise.

3. You are not committing regularly. As you make these changes, ensure you commit very regularly. If you do not commit regularly, your project will not be approved and you may be asked to restart the project.

4. Please edit the title of this PR to a more descriptive title e.g **full feature of mint signup clone**

5. You should add a live link to your readme. You can generate one [here](https://raw.githack.com).

6. Consider increasing the width of your form and adjusting the font-size of your text in the section below so that it will fall into one line as it is on the original page.
image

7. Add some margin between the two sections captured below:
image

8. Check the left alignment of your labels, they should start at the same point with the input fields.

- Please when naming your repositories, try to use a better descriptive name. For example, **Intuit Signup Clone** is a better repository name than **display-inputting-data**. You can rename your current project as well from the settings page.

_**Kindly make these adjustments and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Good job working on the requested changes, but we haven't taken care of them completely yet.**

1. Stickler is still not enabled yet for this repository. You have the right files now. Visit http://stickler-ci.com/ to enable stickler for this repository.

2. Compare the margin above the "LEGAL PRIVACY SECURITY" links with that in the original. You need to add some more margin there.

**Original:**
image

**Yours:**
image

**Review by nikasulo — COMMENTED** [review]
# Nice work! @ricardo123321 and @tacodtripe 
You've done great with the changes, however, stickler isn't enabled on your repo and as such you can't mege just yet

**Review by nikasulo — CHANGES_REQUESTED** [review]
#### Stickler Config
For more information about how to enable it, please look [here](https://github.com/microverseinc/linters-config) for the configuration tailored to the HTML and CSS section.

**Review by kobiyoyo — APPROVED** [review]
# Project Approved :thumbsup:
## Hello Team ,  You have done a great job with this project. :clap:

**Pull request merged**
